#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
source $scriptDir'/../lib/lib'
prepare_colors

prefix_command() {
    if [ -n "$BASH_COMMAND" ] && [ "$BASH_COMMAND" != "$PROMPT_COMMAND" ]; then
        echo
    fi
}

trap 'prefix_command' DEBUG

fetch_weather_data &

prompt_cmd() {
    WEATHER_FILE="/tmp/weather_data_001.txt"
    if [ -f "$WEATHER_FILE" ]; then
        WEATHER_DATA=$(cat "$WEATHER_FILE")
        TEMPERATURE=$(echo "$WEATHER_DATA" | awk '{print $1}')
        WEATHER_DESC=$(echo "$WEATHER_DATA" | awk '{print $2}')
    fi
    DATETIME_1="$(short_date) $(short_time)"
    LINE_1="$(rgb_bg $palette_variant_1) $(no_color) $(rgb_gradient $palette_gradient_start $palette_gradient_end $(current_user)@$HOSTNAME)$(rgb_fg $palette_accent) >> $(rgb_gradient $palette_gradient_start $palette_gradient_end $(basename $PWD)) "
    LINE_2="$(rgb_bg $palette_variant_2) $(no_color) $(rgb_gradient $palette_gradient_start $palette_gradient_end $DATETIME_1) $(rgb_fg $palette_accent)$(gitbranch)$(rgb_fg $palette_secondary)$TEMPERATURE°C $WEATHER_DESC"
    LINE_3="$(rgb_bg $palette_variant_3) $(no_color) $(rgb_fg $palette_accent)$ $(rgb_fg $palette_text)"
    
    PS1="\r\n${LINE_1}\r\n${LINE_2}\r\n${LINE_3}"
}

export PROMPT_COMMAND='prompt_cmd'
